using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AfoCompanion.Utilities
{
    public static class CountriesHelper
    {
        public static Dictionary<string, string> listOfCountries = new Dictionary<string, string>();

        public static void initialiseCountries()
        {

            if (!listOfCountries.ContainsKey("US"))
            {
                listOfCountries.Add("~Daniel's Kingdom", "Canada");
                listOfCountries.Add("US", "United States");
                listOfCountries.Add("CA", "Canada");
                listOfCountries.Add("GB", "United Kingdom");
                listOfCountries.Add("FR", "France");
                listOfCountries.Add("DE", "Germany");
                listOfCountries.Add("IT", "Italy");
                listOfCountries.Add("ES", "Spain");
                listOfCountries.Add("SE", "Sweden");
                listOfCountries.Add("DK", "Denmark");
                listOfCountries.Add("NL", "Netherlands");
                listOfCountries.Add("PL", "Poland");
                listOfCountries.Add("RU", "Russia");
                listOfCountries.Add("TR", "Turkey");
                listOfCountries.Add("AU", "Australia");
                listOfCountries.Add("NZ", "New Zealand");
                listOfCountries.Add("MX", "Mexico");
                listOfCountries.Add("CN", "China");
                listOfCountries.Add("JP", "Japan");
                listOfCountries.Add("KR", "South Korea");
                listOfCountries.Add("IN", "India");
                listOfCountries.Add("AF", "Afghanistan");
                listOfCountries.Add("AX", "Aland Islands");
                listOfCountries.Add("AL", "Albania");
                listOfCountries.Add("DZ", "Algeria");
                listOfCountries.Add("AS", "American Samoa");
                listOfCountries.Add("AD", "Andorra");
                listOfCountries.Add("AO", "Angola");
                listOfCountries.Add("AI", "Anguilla");
                listOfCountries.Add("AQ", "Antarctica");
                listOfCountries.Add("AG", "Antigua and Barbuda");
                listOfCountries.Add("AR", "Argentina");
                listOfCountries.Add("AM", "Armenia");
                listOfCountries.Add("AW", "Aruba");
                listOfCountries.Add("AT", "Austria");
                listOfCountries.Add("AZ", "Azerbaijan");
                listOfCountries.Add("BS", "Bahamas");
                listOfCountries.Add("BH", "Bahrain");
                listOfCountries.Add("BD", "Bangladesh");
                listOfCountries.Add("BB", "Barbados");
                listOfCountries.Add("BY", "Belarus");
                listOfCountries.Add("BE", "Belgium");
                listOfCountries.Add("BZ", "Belize");
                listOfCountries.Add("BJ", "Benin");
                listOfCountries.Add("BM", "Bermuda");
                listOfCountries.Add("BT", "Bhutan");
                listOfCountries.Add("BO", "Bolivia");
                listOfCountries.Add("VG", "British Virgin Islands");
                listOfCountries.Add("BA", "Bosnia and Herzegovina");
                listOfCountries.Add("BW", "Botswana");
                listOfCountries.Add("BV", "Bouvet Island");
                listOfCountries.Add("BR", "Brazil");
                listOfCountries.Add("IO", "British Indian Ocean Territory");
                listOfCountries.Add("BN", "Brunei Darussalam");
                listOfCountries.Add("BG", "Bulgaria");
                listOfCountries.Add("BF", "Burkina Faso");
                listOfCountries.Add("BI", "Burundi");
                listOfCountries.Add("KH", "Cambodia");
                listOfCountries.Add("CM", "Cameroon");
                listOfCountries.Add("CV", "Cape Verde");
                listOfCountries.Add("BQ", "Caribbean Netherlands");
                listOfCountries.Add("KY", "Cayman Islands");
                listOfCountries.Add("CF", "Central African Republic");
                listOfCountries.Add("TD", "Chad");
                listOfCountries.Add("CL", "Chile");
                listOfCountries.Add("CX", "Christmas Island");
                listOfCountries.Add("CC", "Cocos (Keeling) Islands");
                listOfCountries.Add("MF", "Collectivity of Saint Martin");
                listOfCountries.Add("CO", "Colombia");
                listOfCountries.Add("KM", "Comoros");
                listOfCountries.Add("CG", "Congo-Brazzaville");
                listOfCountries.Add("CD", "Congo-Kinshasa");
                listOfCountries.Add("CK", "Cook Islands");
                listOfCountries.Add("CR", "Costa Rica");
                listOfCountries.Add("CI", "Ivory Coast");
                listOfCountries.Add("HR", "Croatia");
                listOfCountries.Add("CU", "Cuba");
                listOfCountries.Add("CW", "Curacao");
                listOfCountries.Add("CY", "Cyprus");
                listOfCountries.Add("CZ", "Czech Republic");
                listOfCountries.Add("DJ", "Djibouti");
                listOfCountries.Add("DM", "Dominica");
                listOfCountries.Add("DO", "Dominican Republic");
                listOfCountries.Add("EC", "Ecuador");
                listOfCountries.Add("EG", "Egypt");
                listOfCountries.Add("SV", "El Salvador");
                listOfCountries.Add("GQ", "Equatorial Guinea");
                listOfCountries.Add("ER", "Eritrea");
                listOfCountries.Add("EE", "Estonia");
                listOfCountries.Add("ET", "Ethiopia");
                listOfCountries.Add("FK", "Falkland Islands");
                listOfCountries.Add("FO", "Faroe Islands");
                listOfCountries.Add("FM", "Federated States of Micronesia");
                listOfCountries.Add("FJ", "Fiji");
                listOfCountries.Add("FI", "Finland");
                listOfCountries.Add("GF", "French Guiana");
                listOfCountries.Add("PF", "French Polynesia");
                listOfCountries.Add("TF", "French Southern Territories");
                listOfCountries.Add("GA", "Gabon");
                listOfCountries.Add("GM", "Gambia");
                listOfCountries.Add("GE", "Georgia");
                listOfCountries.Add("GH", "Ghana");
                listOfCountries.Add("GI", "Gibraltar");
                listOfCountries.Add("GR", "Greece");
                listOfCountries.Add("GL", "Greenland");
                listOfCountries.Add("GD", "Grenada");
                listOfCountries.Add("GP", "Guadeloupe");
                listOfCountries.Add("GU", "Guam");
                listOfCountries.Add("GT", "Guatemala");
                listOfCountries.Add("GG", "Guernsey");
                listOfCountries.Add("GN", "Guinea");
                listOfCountries.Add("GW", "Guinea-Bissau");
                listOfCountries.Add("GY", "Guyana");
                listOfCountries.Add("HT", "Haiti");
                listOfCountries.Add("HM", "Heard Island and McDonald Islands");
                listOfCountries.Add("HN", "Honduras");
                listOfCountries.Add("HK", "Hong Kong");
                listOfCountries.Add("HU", "Hungary");
                listOfCountries.Add("IS", "Iceland");
                listOfCountries.Add("ID", "Indonesia");
                listOfCountries.Add("IR", "Iran");
                listOfCountries.Add("IQ", "Iraq");
                listOfCountries.Add("IE", "Ireland");
                listOfCountries.Add("IM", "Isle of Man");
                listOfCountries.Add("IL", "Israel");
                listOfCountries.Add("JM", "Jamaica");
                listOfCountries.Add("JE", "Jersey");
                listOfCountries.Add("JO", "Jordan");
                listOfCountries.Add("KZ", "Kazakhstan");
                listOfCountries.Add("KE", "Kenya");
                listOfCountries.Add("KI", "Kiribati");
                listOfCountries.Add("KW", "Kuwait");
                listOfCountries.Add("KG", "Kyrgyzstan");
                listOfCountries.Add("LA", "Laos");
                listOfCountries.Add("LV", "Latvia");
                listOfCountries.Add("LB", "Lebanon");
                listOfCountries.Add("LS", "Lesotho");
                listOfCountries.Add("LR", "Liberia");
                listOfCountries.Add("LY", "Libya");
                listOfCountries.Add("LI", "Liechtenstein");
                listOfCountries.Add("LT", "Lithuania");
                listOfCountries.Add("LU", "Luxembourg");
                listOfCountries.Add("MO", "Macao");
                listOfCountries.Add("MK", "Republic of Macedonia");
                listOfCountries.Add("MG", "Madagascar");
                listOfCountries.Add("MW", "Malawi");
                listOfCountries.Add("MY", "Malaysia");
                listOfCountries.Add("MV", "Maldives");
                listOfCountries.Add("ML", "Mali");
                listOfCountries.Add("MT", "Malta");
                listOfCountries.Add("MH", "Marshall Islands");
                listOfCountries.Add("MQ", "Martinique");
                listOfCountries.Add("MR", "Mauritania");
                listOfCountries.Add("MU", "Mauritius");
                listOfCountries.Add("YT", "Mayotte");
                listOfCountries.Add("MD", "Moldova");
                listOfCountries.Add("MC", "Monaco");
                listOfCountries.Add("MN", "Mongolia");
                listOfCountries.Add("ME", "Montenegro");
                listOfCountries.Add("MS", "Montserrat");
                listOfCountries.Add("MA", "Morocco");
                listOfCountries.Add("MZ", "Mozambique");
                listOfCountries.Add("MM", "Myanmar");
                listOfCountries.Add("NA", "Namibia");
                listOfCountries.Add("NR", "Nauru");
                listOfCountries.Add("NP", "Nepal");
                listOfCountries.Add("NC", "New Caledonia");
                listOfCountries.Add("NI", "Nicaragua");
                listOfCountries.Add("NE", "Niger");
                listOfCountries.Add("NG", "Nigeria");
                listOfCountries.Add("NU", "Niue");
                listOfCountries.Add("NF", "Norfolk Island");
                listOfCountries.Add("KP", "North Korea");
                listOfCountries.Add("MP", "Northern Mariana Islands");
                listOfCountries.Add("NO", "Norway");
                listOfCountries.Add("OM", "Oman");
                listOfCountries.Add("PK", "Pakistan");
                listOfCountries.Add("PW", "Palau");
                listOfCountries.Add("PS", "Palestinian Territory");
                listOfCountries.Add("PA", "Panama");
                listOfCountries.Add("PG", "Papua New Guinea");
                listOfCountries.Add("PY", "Paraguay");
                listOfCountries.Add("PE", "Peru");
                listOfCountries.Add("PH", "Philippines");
                listOfCountries.Add("PN", "Pitcairn");
                listOfCountries.Add("PT", "Portugal");
                listOfCountries.Add("PR", "Puerto Rico");
                listOfCountries.Add("QA", "Qatar");
                listOfCountries.Add("RE", "Reunion");
                listOfCountries.Add("RO", "Romania");
                listOfCountries.Add("RW", "Rwanda");
                listOfCountries.Add("BL", "Saint Barthelemy");
                listOfCountries.Add("SH", "Saint Helena");
                listOfCountries.Add("KN", "Saint Kitts and Nevis");
                listOfCountries.Add("LC", "Saint Lucia");
                listOfCountries.Add("PM", "Saint Pierre and Miquelon");
                listOfCountries.Add("VC", "Saint Vincent and the Grenadines");
                listOfCountries.Add("WS", "Samoa");
                listOfCountries.Add("SM", "San Marino");
                listOfCountries.Add("ST", "Sao Tome and Principe");
                listOfCountries.Add("SA", "Saudi Arabia");
                listOfCountries.Add("SN", "Senegal");
                listOfCountries.Add("RS", "Serbia");
                listOfCountries.Add("SC", "Seychelles");
                listOfCountries.Add("SL", "Sierra Leone");
                listOfCountries.Add("SG", "Singapore");
                listOfCountries.Add("SX", "Sint Maarten");
                listOfCountries.Add("SK", "Slovakia");
                listOfCountries.Add("SI", "Slovenia");
                listOfCountries.Add("SB", "Solomon Islands");
                listOfCountries.Add("SO", "Somalia");
                listOfCountries.Add("ZA", "South Africa");
                listOfCountries.Add("GS", "South Georgia and the South Sandwich Islands");
                listOfCountries.Add("SS", "South Sudan");
                listOfCountries.Add("LK", "Sri Lanka");
                listOfCountries.Add("SD", "Sudan");
                listOfCountries.Add("SR", "Suriname");
                listOfCountries.Add("SJ", "Svalbard and Jan Mayen");
                listOfCountries.Add("SZ", "Swaziland");
                listOfCountries.Add("CH", "Switzerland");
                listOfCountries.Add("SY", "Syrian Arab Republic");
                listOfCountries.Add("TW", "Taiwan");
                listOfCountries.Add("TJ", "Tajikistan");
                listOfCountries.Add("TZ", "Tanzania");
                listOfCountries.Add("TH", "Thailand");
                listOfCountries.Add("TL", "Timor-Leste");
                listOfCountries.Add("TG", "Togo");
                listOfCountries.Add("TK", "Tokelau");
                listOfCountries.Add("TO", "Tonga");
                listOfCountries.Add("TT", "Trinidad and Tobago");
                listOfCountries.Add("VN", "Tristan da Cunha");
                listOfCountries.Add("TN", "Tunisia");
                listOfCountries.Add("TM", "Turkmenistan");
                listOfCountries.Add("TC", "Turks and Caicos Islands");
                listOfCountries.Add("TV", "Tuvalu");
                listOfCountries.Add("UG", "Uganda");
                listOfCountries.Add("UA", "Ukraine");
                listOfCountries.Add("AE", "United Arab Emirates");
                listOfCountries.Add("UM", "United States Minor Outlying Islands");
                listOfCountries.Add("UY", "Uruguay");
                listOfCountries.Add("UZ", "Uzbekistan");
                listOfCountries.Add("VU", "Vanuatu");
                listOfCountries.Add("VA", "Vatican City");
                listOfCountries.Add("VE", "Venezuela");
                listOfCountries.Add("VI", "Virgin Islands, U.S.");
                listOfCountries.Add("WF", "Wallis and Futuna");
                listOfCountries.Add("EH", "Western Sahara");
                listOfCountries.Add("YE", "Yemen");
                listOfCountries.Add("ZM", "Zambia");
                listOfCountries.Add("ZW", "Zimbabwe");
            }
            
        }

        public static string getCountry(string abbr)
        {
            return listOfCountries[abbr];
        }
    }
}